Repository OpenVoiceOS/ovos-personal-backend, pull requests merged in 2022-10, with the labels that each got.

#37 feat/ww_tags
  ovos_local_backend/backend/device.py
  ovos_local_backend/database/wakewords.py
Labels: enhancement

#36 feat/oauth
  ovos_local_backend/backend/auth.py
  ovos_local_backend/database/oauth.py
  requirements/requirements.txt
Labels: enhancement

#35 refactor/selene_api -> ovos-backend-client
  README.md
  ovos_local_backend/backend/decorators.py
  ovos_local_backend/backend/device.py
  ovos_local_backend/utils/__init__.py
  ovos_local_backend/utils/mail.py
  ovos_local_backend/utils/selene.py
  requirements/requirements.txt
Labels: enhancement

#39 fix/import
  ovos_local_backend/utils/geolocate.py
Labels: bug

#40 fix/handle_ipgeo_failures
  ovos_local_backend/backend/device.py
  ovos_local_backend/utils/geolocate.py
Labels: bug

#41 Fix weather one call from remote device
  ovos_local_backend/__main__.py
  ovos_local_backend/backend/external_apis.py
  ovos_local_backend/utils/__init__.py
Labels: bug

#43 Fix/selene UUID
  ovos_local_backend/database/settings.py
  ovos_local_backend/utils/selene.py
Labels: bug

#44 Feat/workflows
  .github/workflows/build_tests.yml
  .github/workflows/license_tests.yml
  test/license_tests.py
Labels: automations and tests
